# Pandas

In [1]:
#Create a series with five fruits names as their prices where fruit name should be index

import pandas as pd
a = pd.Series([200,150,120,50,60], index=['DragonFruit' , 'Litchi' , 'Blackberry' , 'Banana' , 'Mango'])
a

DragonFruit    200
Litchi         150
Blackberry     120
Banana          50
Mango           60
dtype: int64

In [2]:
#create a dataframe for 5 students name, marks of 5 subject and rank

b = pd.DataFrame([['Komal',90,89,95,99,85, 1],
               ['Karan',78,67,56,45,87, 3],
               ['Priya', 90,89,79,98,99,2]], index=[1,2,3], columns = ['Name','DAA','Maths','OOPS','DE','COA','Rank'])
b

    Name  DAA  Maths  OOPS  DE  COA  Rank
1  Komal   90     89    95  99   85     1
2  Karan   78     67    56  45   87     3
3  Priya   90     89    79  98   99     2

# Data Loading

In [1]:
import pandas as pd                    #importing the libraries
df = pd.read_csv("D:\mtcars2.csv")     #loading the data
df

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,NaN,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,NaN,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [ ]:
#pd.read_excel
#pd.read_html
#pd.read_pdf
#pd.read_word
#pd.read_json

In [2]:
df.shape

(32, 13)

In [3]:
import pandas as pd                          #importing the libraries
df = pd.read_csv("D:\mtcars2.csv")
df.info

<bound method DataFrame.info of     S.No           Unnamed: 1   mpg  cyl   disp   hp  drat     wt   qsec  vs  \
0      1            Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0
1      2        Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0
2      3           Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1
3      4       Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1
4      5    Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0
5      6              Valiant  18.1    6  225.0  105  2.76  3.460    NaN   1
6      7           Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0
7      8            Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1
8      9             Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1
9     10             Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1
10    11            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1
11    12           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0
12    13           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0
13    14          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0
14    15   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0
15    16  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0
16    17    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0
17    18             Fiat 128  32.4    4   78.7   66  4.08  2.200    NaN   1
18    19          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1
19    20       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1
20    21        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1
21    22     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0
22    23          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0
23    24           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0
24    25     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0
25    26            Fiat X1-9  27.3    4   79.0   66  4.08  1.935    NaN   1
26    27        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0
27    28         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1
28    29       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0
29    30         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0
30    31        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0
31    32           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1

    am  gear  carb
0    1     4     4
1    1     4     4
2    1     4     1
3    0     3     1
4    0     3     2
5    0     3     1
6    0     3     4
7    0     4     2
8    0     4     2
9    0     4     4
10   0     4     4
11   0     3     3
12   0     3     3
13   0     3     3
14   0     3     4
15   0     3     4
16   0     3     4
17   1     4     1
18   1     4     2
19   1     4     1
20   0     3     1
21   0     3     2
22   0     3     2
23   0     3     4
24   0     3     2
25   1     4     1
26   1     5     2
27   1     5     2
28   1     5     4
29   1     5     6
30   1     5     8
31   1     4     2  >

# Data Info Gathering

In [4]:
df.head()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [5]:
df.tail()

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [6]:
df.head(9)

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,NaN,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2

In [7]:
df.min()

S.No                    1
Unnamed: 1    AMC Javelin
mpg                  10.4
cyl                     4
disp                 71.1
hp                     52
drat                 2.76
wt                  1.513
qsec                 14.5
vs                      0
am                      0
gear                    3
carb                    1
dtype: object

In [8]:
df.max()

S.No                  32
Unnamed: 1    Volvo 142E
mpg                 33.9
cyl                    8
disp               472.0
hp                   335
drat                4.93
wt                 5.424
qsec                22.9
vs                     1
am                     1
gear                   5
carb                   8
dtype: object

In [9]:
df.describe()

,S.No,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,29.000000,32.000000,32.000000,32.000000,32.0000
mean,16.500000,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.674828,0.437500,0.406250,3.687500,2.8125
std,9.380832,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.780394,0.504016,0.498991,0.737804,1.6152
min,1.000000,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,8.750000,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.870000,0.000000,0.000000,3.000000,2.0000
50%,16.500000,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.420000,0.000000,0.000000,4.000000,2.0000
75%,24.250000,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.600000,1.000000,1.000000,4.000000,4.0000
max,32.000000,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [10]:
df.mpg.median()

19.2

In [11]:
df.count()

S.No          32
Unnamed: 1    32
mpg           32
cyl           32
disp          32
hp            32
drat          32
wt            32
qsec          29
vs            32
am            32
gear          32
carb          32
dtype: int64

In [12]:
#missing value in dataset:-->

#can be fill by mean, median, mode
#median becoz it will not affect the data too much . eg 1,2,3,4,5,... mean-3 median -3 .. if 1,2,3,4,5,100 then mean-19.5 median -3.5
#differnce is clear after adding 1 value there is a long differnce in mean and can affect the data

# Data Cleaning

In [13]:
df.isnull().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          3
vs            0
am            0
gear          0
carb          0
dtype: int64

In [15]:
y=df.qsec.median()
y

17.42

In [18]:
df.fillna({'qsec':y},inplace = True)

,S.No,Unnamed: 1,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,1,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,2,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,3,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,4,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,5,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,6,Valiant,18.1,6,225.0,105,2.76,3.460,17.42,1,0,3,1
6,7,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,8,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,9,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,10,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,11,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,12,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,13,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,14,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,15,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,16,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,17,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,18,Fiat 128,32.4,4,78.7,66,4.08,2.200,17.42,1,1,4,1
18,19,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,20,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,21,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,22,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,23,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,24,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,25,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,26,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,17.42,1,1,4,1
26,27,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,28,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,29,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,30,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,31,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,32,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [19]:
df.isnull().sum()

S.No          0
Unnamed: 1    0
mpg           0
cyl           0
disp          0
hp            0
drat          0
wt            0
qsec          0
vs            0
am            0
gear          0
carb          0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)